"""single user object, many-to-many user-category relationship

Revision ID: 472711fce0ac
Revises: b81f6d8cc11f
Create Date: 2021-08-14 14:09:17.682317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '472711fce0ac'
down_revision = 'b81f6d8cc11f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_name', sa.String(length=70), nullable=True),
    sa.Column('org_purpose', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('start_up', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=70), nullable=True),
    sa.Column('claimed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_location'), 'user', ['location'], unique=False)
    op.create_index(op.f('ix_user_org_name'), 'user', ['org_name'], unique=True)
    op.create_index(op.f('ix_user_start_up'), 'user', ['start_up'], unique=False)
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('category_id', 'user_id')
    )
    op.drop_index('ix_start_up_category', table_name='start_up')
    op.drop_index('ix_start_up_city', table_name='start_up')
    op.drop_index('ix_start_up_email', table_name='start_up')
    op.drop_index('ix_start_up_org_name', table_name='start_up')
    op.drop_table('start_up')
    op.drop_index('ix_student_group_category', table_name='student_group')
    op.drop_index('ix_student_group_email', table_name='student_group')
    op.drop_index('ix_student_group_org_name', table_name='student_group')
    op.drop_index('ix_student_group_school', table_name='student_group')
    op.drop_table('student_group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_group',
    sa.Column('org_name', sa.VARCHAR(length=70), nullable=True),
    sa.Column('org_purpose', sa.VARCHAR(length=500), nullable=True),
    sa.Column('category', sa.INTEGER(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('claimed', sa.BOOLEAN(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('school', sa.VARCHAR(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_student_group_school', 'student_group', ['school'], unique=False)
    op.create_index('ix_student_group_org_name', 'student_group', ['org_name'], unique=False)
    op.create_index('ix_student_group_email', 'student_group', ['email'], unique=False)
    op.create_index('ix_student_group_category', 'student_group', ['category'], unique=False)
    op.create_table('start_up',
    sa.Column('org_name', sa.VARCHAR(length=70), nullable=True),
    sa.Column('org_purpose', sa.VARCHAR(length=500), nullable=True),
    sa.Column('category', sa.INTEGER(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('claimed', sa.BOOLEAN(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('city', sa.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_start_up_org_name', 'start_up', ['org_name'], unique=False)
    op.create_index('ix_start_up_email', 'start_up', ['email'], unique=False)
    op.create_index('ix_start_up_city', 'start_up', ['city'], unique=False)
    op.create_index('ix_start_up_category', 'start_up', ['category'], unique=False)
    op.drop_table('categories')
    op.drop_index(op.f('ix_user_start_up'), table_name='user')
    op.drop_index(op.f('ix_user_org_name'), table_name='user')
    op.drop_index(op.f('ix_user_location'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('category')
    # ### end Alembic commands ###
