"""changed User to Organization

Revision ID: 5a2cf0e3e9c0
Revises: 4f2ebf8ad1c2
Create Date: 2021-08-26 22:43:48.321699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a2cf0e3e9c0'
down_revision = '4f2ebf8ad1c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_name'), ['name'], unique=False)

    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_name', sa.String(length=70), nullable=True),
    sa.Column('org_purpose', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_start_up', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=70), nullable=True),
    sa.Column('claimed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_organization_is_start_up'), ['is_start_up'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_org_name'), ['org_name'], unique=True)

    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('category_id', 'organization_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_org_name'))
        batch_op.drop_index(batch_op.f('ix_organization_location'))
        batch_op.drop_index(batch_op.f('ix_organization_is_start_up'))
        batch_op.drop_index(batch_op.f('ix_organization_email'))

    op.drop_table('organization')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_name'))

    op.drop_table('category')
    # ### end Alembic commands ###
