"""renamed properties

Revision ID: 84278d4b2703
Revises: 5a2cf0e3e9c0
Create Date: 2021-08-26 22:45:14.443264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84278d4b2703'
down_revision = '5a2cf0e3e9c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=70), nullable=True))
        batch_op.add_column(sa.Column('purpose', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))
        batch_op.drop_index('ix_organization_org_name')
        batch_op.create_index(batch_op.f('ix_organization_name'), ['name'], unique=True)
        batch_op.drop_column('claimed')
        batch_op.drop_column('org_name')
        batch_op.drop_column('org_purpose')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_purpose', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('org_name', sa.VARCHAR(length=70), nullable=True))
        batch_op.add_column(sa.Column('claimed', sa.BOOLEAN(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_organization_name'))
        batch_op.create_index('ix_organization_org_name', ['org_name'], unique=False)
        batch_op.drop_column('verified')
        batch_op.drop_column('purpose')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
